Add possibility work with different path segments
magdevelopment/StageHostSelector pull request #3
Opened 2020-01-14 09:38 UTC by Grue1ing

Add possibility add default urls into dialog

2020-01-14 10:25 UTC, orteney requested changes

2020-01-14 10:25 UTC, orteney commented on sampleapp/src/main/java/com/magdv/stagehostselector/sampleapp/MainActivity.kt
> +        view.suggestedUrls = suggestedUrls
Может без промежуточной переменной

2020-01-14 10:25 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/dialog/StageHostSelectorDialogFragment.kt
> +        addDefaultSuggestionUrls()
Лучше не добавлять их каждый раз туда :<

2020-01-14 10:25 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/dialog/StageHostSelectorDialogFragment.kt
> +        }
Надо бы их сохранить обратно в префсы, после добавления

2020-01-14 10:25 UTC, orteney commented on sampleapp/build.gradle
> +        buildConfigField "String", "API_ENDPOINT", '"http://example.com/main/"'
Вернуть как было :<

2020-01-14 10:25 UTC, orteney commented on sampleapp/src/main/java/com/magdv/stagehostselector/sampleapp/MainActivity.kt
> +            "http://example.com:8080/alternative/second"
чот много для примера

2020-01-14 10:25 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/dialog/StageHostSelectorDialogFragment.kt
> +
Лишнее, можно просто сделать метод у фрагмента

2020-01-14 10:25 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/interceptor/StageHostSelectorInterceptor.kt
> +            val defaultHostUrlSegmentsCount = HttpUrl.parse(defaultHostUrl)?.pathSegments()?.count() ?: 0
при каждом запросе заного парсится :<

2020-01-14 10:25 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/interceptor/StageHostSelectorInterceptor.kt
> +            val necessaryPartHostUrlSegmentsCount = if (defaultHostUrlSegmentsCount == 0) 0 else defaultHostUrlSegmentsCount - 1
min(0, defaultHostUrlSegmentsCount - 1)

2020-01-14 10:25 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/interceptor/StageHostSelectorInterceptor.kt
> +                pathSegments += "${chain.request().url().pathSegments()[i]}/"
Вынести бы получение списка сегментов из цикла

2020-01-14 10:25 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/interceptor/StageHostSelectorInterceptor.kt
> +            }
Простым выпиливанием количества сегментов можно сломать фичу ретрофита, когда для запроса игнорируются сегменты указанные в базовом урле. (например `@GET("/neuser/logout")`). Придется сравнивать сегменты перед тем как их удалять х)

2020-01-14 10:25 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/view/StageHostSelectorView.kt
> +    var suggestedUrls: MutableSet<String> = mutableSetOf()
Лучше вынести эту фичу в другой PR

2020-01-14 10:56 UTC, Grue1ing commented on stagehostselector/src/main/java/com/magdv/stagehostselector/interceptor/StageHostSelectorInterceptor.kt
> +            val necessaryPartHostUrlSegmentsCount = if (defaultHostUrlSegmentsCount == 0) 0 else defaultHostUrlSegmentsCount - 1
max

2020-01-15 03:19 UTC, Grue1ing commented on stagehostselector/src/main/java/com/magdv/stagehostselector/view/StageHostSelectorView.kt
> +    var suggestedUrls: MutableSet<String> = mutableSetOf()
давай зарезолвим тут и потом разобью на два, или проблоема именно в чтении?

2020-01-15 04:07 UTC, orteney requested changes

2020-01-15 04:07 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/dialog/StageHostSelectorDialogFragment.kt
> +        addDefaultSuggestionUrls()
чот вроде addsuggestionurls, а под капотом не всегда add 🗡

2020-01-15 04:07 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/interceptor/StageHostSelectorInterceptor.kt
> +        val newRequest = cachedHostHttpUrl?.let { cachedHostHttpUrl ->
может early exit замутим

2020-01-15 04:07 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/view/StageHostSelectorView.kt
> +    var suggestedUrls: MutableSet<String> = mutableSetOf()
не

2020-01-15 12:13 UTC, closed without merging