Add possibility add default urls into dialog
magdevelopment/StageHostSelector pull request #5
Opened 2020-01-15 10:21 UTC by Grue1ing

2020-01-15 10:42 UTC, orteney requested changes

2020-01-15 10:42 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/repository/StageHostSelectorRepository.kt
> +    fun getCurrentHostUrl(): String? {
Надо тогда в интерсепторе это дергать

2020-01-16 04:41 UTC, orteney requested changes

2020-01-16 04:41 UTC, orteney commented on sampleapp/src/main/java/com/magdv/stagehostselector/sampleapp/MainActivity.kt
> +        initStageHostSelector()
Надо в Application.onCreate унести х(

2020-01-16 04:41 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/StageHostSelector.kt
> + * Project: MAG.Express
???

2020-01-16 04:41 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/repository/StageHostSelectorRepository.kt
>  ) {
Предлагаю 
- убрать сингльтон
- оставить префсы + передавать в конструктор дефурл и дефсагешны

2020-01-16 11:26 UTC, orteney requested changes

2020-01-16 11:26 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/repository/StageHostSelectorRepositoryImpl.kt
> +    }
а чем это отличается от просто `listener?.onValueChanged(getCurrentHostUrl() ?: getDefaultHostUrl())`

2020-01-16 11:26 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/repository/StageHostSelectorRepositoryImpl.kt
> +        private var url: String? = null
непонятно почему это тут

2020-01-16 11:26 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/view/StageHostSelectorView.kt
> +    override fun onValueChanged(newCurrentHostUrl: String?) {
название неоч)

2020-01-16 11:26 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/StageHostSelector.kt
> +            }
Чот перспектива существания какой-то пустой вьюшки в продовом коде такая себе :<
Лучше уж тогда null вернуть

2020-01-16 12:01 UTC, Grue1ing commented on stagehostselector/src/main/java/com/magdv/stagehostselector/repository/StageHostSelectorRepositoryImpl.kt
> +    }
каждый раз когда в обсервабл сетится новое значение он сообщает лисенеру, обсервабл тут создается чтобы пихать в него значения на 20 строке

2020-01-16 12:03 UTC, Grue1ing commented on stagehostselector/src/main/java/com/magdv/stagehostselector/repository/StageHostSelectorRepositoryImpl.kt
> +        private var url: String? = null
потому что оно тут инициализируется

2020-01-17 04:17 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/repository/StageHostSelectorRepositoryImpl.kt
> +    }
ну тип какой смысл в дополнительной обертке, если можно просто дергать метод у листенера?)

2020-01-17 04:18 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/repository/StageHostSelectorRepositoryImpl.kt
> +        private var url: String? = null
я к тому, что это можно в конструктор убрать

2020-01-17 08:52 UTC, orteney requested changes

2020-01-17 08:52 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/StageHostSelector.kt
> +        }
можно же return `repository?.let { ...(it, cotntext) }`

2020-01-17 08:52 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/repository/StageHostSelectorRepositoryImpl.kt
> +        private var instance: StageHostSelectorRepositoryImpl? = null
Зачем он здесь?

2020-01-21 03:24 UTC, orteney commented on stagehostselector/src/main/java/com/magdv/stagehostselector/repository/StageHostSelectorRepositoryImpl.kt
> +        private var instance: StageHostSelectorRepositoryImpl? = null
:<<<

2020-01-21 03:36 UTC, merged